Authors: mfrias && oldurosi

In [2]:
import numpy as np
import matplotlib as mp

<br>

1. Create a matrix of random values of a distribution of your choice.

In [9]:
randmatrice = np.random.randint(10, size=(3,2))

In [10]:
randmatrice

array([[0, 1],
       [9, 6],
       [1, 7]])

<br>

2. Create a 1-dimensional array of 12 sequential numbers and convert it to a 4x3 array.

In [15]:
array1 = np.arange(1, 13)

In [16]:
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [19]:
array1.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

<br>

3. Write a function that creates an incremental N-dimensional (nd) array of dimension (1,n) with values between 0    and 1. Use arr.shape to verify

In [4]:
def NdimensionArrayfunction(n):
    return np.full((1, n), np.linspace(0, 1, n))

In [5]:
formingarray = NdimensionArrayfunction(5)

In [6]:
formingarray

array([[0.  , 0.25, 0.5 , 0.75, 1.  ]])

In [7]:
formingarray.shape

(1, 5)

<br>

4. Generate a 10x12 array and extract row 0-4 of columns 8-12.
